name: biosc1630-2024f-dev
channels:
  - defaults
dependencies:
  - python=3.12
  - conda-lock
  - conda-forge::poetry
  - conda-forge::pre-commit
  - conda-forge::conda-poetry-liaison
  - conda-forge::nodejs
